rango/urls.py
from django.conf.urls import url

from . import views


app_name = 'rango'
urlpatterns=[
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$',
        views.show_category, name='show_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$',
        views.add_page, name='add_page'),
    # url(r'^register/$', views.register, name='register'),
    # url(r'^login/$', views.user_login, name='login'),
    # url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^restricted/$', views.restricted, name='restricted'),
    url(r'^goto/$', views.track_url, name='goto'),
    url(r'^register_profile/$', views.register_profile, name='register_profile'),
    url(r'^profile/(?P<username>[\w\s]+)/$', views.profile, name='profile'),
    url(r'^profile/$', views.show_profile, name='show_profile'),
]

tango_with_django_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import reverse
from registration.backends.simple.views import RegistrationView


class MyRegistrationView(RegistrationView):

    def get_success_url(self, user):
        return reverse('rango:register_profile')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^rango/', include('rango.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(),
        name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Page, Category, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text="Please enter the category name:",)
    views = forms.IntegerField(widget=forms.HiddenInput, initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput, initial=0)
    slug = forms.CharField(widget=forms.HiddenInput, required=False)

    class Meta:
        model = Category
        fields = ('name',) #tuple


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="Please enter the title of the page:")
    url = forms.URLField(max_length=200,
                         help_text="Please enter the URL of the page:")
    views = forms.IntegerField(widget=forms.HiddenInput, initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

        return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from datetime import datetime

from django.shortcuts import render, reverse, redirect
# from django.http import HttpResponse, HttpResponseRedirect
# from django.contrib.auth import authenticate, login, logout
# from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from .models import Category, Page, UserProfile
from .forms import CategoryForm, PageForm, UserForm, UserProfileForm


'''将信息储存在客户端的cookie中'''
# def vistor_cookie_handler(request, response):
#     visits = int(request.COOKIES.get('visits', '1'))
#
#     last_visit_cookie = request.COOKIES.get('last_visit', str(datetime.now()))
#     last_visit_time = datetime.strptime(last_visit_cookie[:-7],
#                                         '%Y-%m-%d %H:%M:%S')
#
#     if (datetime.now() - last_visit_time).seconds > 0:
#         visits += 1
#         response.set_cookie('last_visit', str(datetime.now()))
#     else:
#         response.set_cookie('last_visit', last_visit_cookie)
#
#     response.set_cookie('visits', visits)


def get_server_side_cookie(request, cookie, default_val=None):
    """将信息储存在服务端的session中"""
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))

    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                        '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).seconds > 0:
        visits += 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits


def index(request):
    # request.session.set_test_cookie()
    context = {}
    context['categories'] = Category.objects.order_by('-likes')[:5]
    context['pages'] = Page.objects.order_by('-views')[:5]
    visitor_cookie_handler(request)
    context['visits'] = request.session.get('visits')

    return render(request, 'rango/index.html', context=context)


def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None
    else:
        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict['category'] = category
        context_dict['pages'] = pages

    return render(request, 'rango/category.html', context=context_dict)


@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', context={'form': form})


@login_required
def add_page(request, category_name_slug):
    try:
        cat = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        cat = None

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if cat:
                page = form.save(commit=False)
                page.category = cat
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)

    context_list = {'form': form, 'category': cat}
    return render(request, 'rango/add_page.html', context=context_list)


# def register(request):
#     user_form = UserForm()
#     profile_form = UserProfileForm()
#     registered = False
#
#     if request.method == 'POST':
#         user_form = UserForm(request.POST)
#         profile_form = UserProfileForm(request.POST)
#
#         if user_form.is_valid() and profile_form.is_valid():
#             user = user_form.save()
#             user.set_password(user.password)
#             user.save()
#
#             profile = profile_form.save(commit=False)
#             profile.user = user
#             if 'picture' in request.FILES:
#                 profile.picture = request.FILES['picture']
#             profile.save()
#
#             registered = True
#         else:
#             print(user_form.errors, profile_form.errors)
#
#     return render(request, 'rango/register.html', {'user_form': user_form,
#                                                    'profile_form': profile_form,
#                                                    'registered': registered})


# def user_login(request):
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#         user = authenticate(username=username, password=password)
#
#         if user:
#             if user.is_active:
#                 login(request, user)
#                 return HttpResponseRedirect(reverse('rango:index'))
#             else:
#                 return render(request, 'rango/login.html',
#                               {'error_msg': 'Your rango account is disabled.'})
#         else:
#             print('Invalid login details: {}, {}'.format(username, password))
#             return render(request, 'rango/login.html',
#                           {'error_msg': 'Invalid login details supplied.'})
#
#     else:
#         return render(request, 'rango/login.html')


# @login_required
# def user_logout(request):
#     logout(request)
#     return HttpResponseRedirect(reverse('rango:index'))


@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')


def track_url(request):
    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
            try:
                page = Page.objects.get(id=page_id)
            except Page.DoesNotExist:
                return redirect('/rango/')
            else:
                page.views = page.views + 1
                page.save()
                return redirect(page.url)

    return redirect('/rango/')


@login_required
def register_profile(request):
    submitted = False
    if request.method == 'POST':
        user = request.user   # 用户相关信息保存在request.user中
        try:
            user_profile = UserProfile.objects.get(user=user)
        except UserProfile.DoesNotExist:
            user_profile = UserProfile(user=user)
        if request.POST['website']:
            user_profile.website = request.POST['website']
            print('submit')
            submitted = True
        if 'picture' in request.FILES:
            user_profile.picture = request.FILES['picture']
            print('picture')
            submitted = True
        user_profile.save()

    return render(request, 'rango/profile_registration.html', {'submitted': submitted})


@login_required
def profile(request, username):
    true_user = 0
    context = {}
    try:
        user_query = User.objects.get(username=username)
        user_profile = UserProfile.objects.get(user=user_query)
    except User.DoesNotExist:
        pass
    except UserProfile.DoesNotExist:
        user = request.user
        if user == user_query:
            true_user = 1
    else:
        context['user_profile'] = user_profile
        user = request.user
        if user == user_query:
            true_user = 2

    context['true_user'] = true_user
    return render(request, 'rango/profile.html', context=context)


@login_required
def show_profile(request):
    context = {}
    try:
        users = User.objects.all().order_by('username')
    except User.DoesNotExist:
        pass
    else:
        context['users'] = users

    return render(request, 'rango/profile_show.html', context)


def about(request):
    # if request.session.test_cookie_worked():
    #     print('TEST COOKIE WORKED!')
    #     request.session.delete_test_cookie()
    print(request.method)
    print(request.user)
    context = {'creator': 'wangfp'}

    visitor_cookie_handler(request)
    context['visits'] = request.session.get('visits')
    return render(request, 'rango/about.html', context=context)

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}
    About
{% endblock %}

{% block body %}
<div class="jumbotron">
    <h1>This tutorial has been put together by
        <strong>{{ creator }}</strong>
    </h1>
    <h4>visits: {{ visits }}</h4>
</div>

    <img src="{{ MEDIA_URL }}default.gif" alt="flag"><br />
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}
    Add New Category
{% endblock %}

{% block body %}
    <div class="jumbotron">
        <h1>Add a New Category</h1>
    </div>
    <div>
        <form role="form" action="{% url 'rango:add_category' %}" id="category_form" method="post">
            <h4 class="form-signin-heading">
                Add New Category Here
            </h4>
            <div class="form-group">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
            {% endfor %}
            </div>
            <button class="btn btn-primary" type="submit" name="submit">Add Category</button>
        </form>
    </div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}
    Add New Page
{% endblock %}

{% block body %}
    {% if category %}
    <hr />
    <div>
        <form role="form" id="page_form" action="{% url 'rango:add_page' category.slug %}" method="post">
        <h2 class="form-signin-heading">
            <a href="{% url 'rango:show_category' category.slug %}">Add a Page to {{ category.name }}</a>
        </h2>
            <div class="form-group">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
            {% endfor %}
            </div>
            <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
        </form>
    </div>
    {% else %}
    <strong>The specified category does not exist!</strong>
    {% endif %}
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v4-alpha.getbootstrap.com/favicon.ico">

    <title>
        Rango -
        {% block title %}
            How to Tango with Djano!
        {% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Dashboard</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'rango:index' %}">Index <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Search</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:show_profile' %}">Profile List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth_logout' %}">Log Out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'registration_register' %}">Register Here</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth_login' %}">Log In</a>
          </li>
          {% endif %}
        </ul>

        <ul class="navbar-nav">
          <li class="nav-item">
            {% if user.is_authenticated %}
            <a href="{% url 'rango:profile' user.username %}" class="text-info">Hello, {{ user.username }}</a>
            {% else %}
            <span class="text-info">Hi, buddy</span>
            {% endif %}
          </li>

        </ul>
<!--        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>-->
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          {% block sidebar %}
            {% get_category_list category %}
          {% endblock %}
        </div>

        <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
          {% block body %}
          {% endblock %}
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
     <!--Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="http://v4-alpha.getbootstrap.com/assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/rango/base_bootstrap.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v4-alpha.getbootstrap.com/favicon.ico">

    <title>Rango - {% block title %}
    How to Tango with Djano!{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Dashboard</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'rango:index' %}">Index <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:search' %}">Search</a>
          </li>
          {% is user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth_logout' %}">Log Out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'registration_register' %}">Register Here</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth_login' %}">Log In</a>
          </li>
        </ul>
        <!--<form class="form-inline mt-2 mt-md-0">-->
          <!--<input class="form-control mr-sm-2" type="text" placeholder="Search">-->
          <!--<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
        <!--</form>-->
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
          {% block sidebar %}
            {% get_category_list category %}
          {% endblock %}
        </nav>

        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
          {% block body %}
          {% endblock %}
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="http://v4-alpha.getbootstrap.com/assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% load bootstrap_toolkit %}

{% block title %}
    {{ category.name }}
{% endblock %}

{% block body %}
    <div class="jumbotron">
        <h1>Show Category</h1>
    </div>

    <div class="row marketing">
        <div class="col-lg-10">
            <h1>{{ category.name }}</h1>
            {% if category %}

                {% if pages %}
                    <ul class="list-group">
                    {% for page in pages %}
                        <li class="list-group-item"><a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }} ({{ page.views }} viewed)</a></li>
                    {% endfor %}
                    </ul>
                {% else %}
                    <strong>No pages currently in category.</strong>
                {% endif %}

                <hr />

                {% if user.is_authenticated %}
                    <a href="{% url 'rango:add_page' category.slug %}" class="btn btn-primary" role="button">Add a new Page</a>
                {% endif %}
            {% else %}
                    <strong>The specified category does not exist!</strong>
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/rango/cats.html
<ul class="nav nav-pills flex-column">
    {% if cats %}
        {% for category in cats %}
            {% if act_cat == category %}
            <li class="nav-item">
                <strong>
                    <a class="nav-link active" href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
                </strong>
            </li>
            {% else %}
            <li class="nav-itme">
                <a class="nav-link" href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
            </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block body %}
<div class="jumbotron">
    <h1>Rango says...
    <span>
        {% if user.is_authenticated %}
            howdy {{ user.username }}!
        {% else %}
            hey there partner!
        {% endif %}
    </span>
    </h1>
    <h3> visits: {{ visits }}</h3>
</div>

<div class="row marketing">
    <div class="col-lg-6">
        <h4>Most Liked Categories</h4>
        {% if categories %}
        <ul class="list-group">
            {% for category in categories %}
            <li class="list-group-item">
                <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
            <strong>There are no category present.</strong>
        {% endif %}
    </div>
    <div class="col-lg-6">
        <h4>Most Viewed Pages</h4>
        {% if pages %}
        <ul class="list-group">
            {% for page in pages %}
            <li class="list-group-item"><a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }} ({{ page.views }} viewed)</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <strong>There are no page yet.</strong>
        {% endif %}
    </div>
</div>
    <div>
        <img src="{% static 'images/rango.gif' %}" />
    </div>
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}
    Login
{% endblock %}

{% block body %}
<div>
    <h1>Login to Rango</h1>
    <div style="color: red">
    {% if error_msg %}
        {{ error_msg }}
    {% endif %}
    </div>
    <form id=login_form" method="post" action="{% url 'rango:login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" size="50" /><br />
        Password: <input type="password" name="password" size="50" /><br />
        <input type="submit" name="submit" value="Login" />
    </form>
</div>
{% endblock %}

templates/rango/profile_registration.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}
    Complete Profile
{% endblock %}

{% block body %}
<div class="jumbotron">
    <h1>Complete Your Profile</h1>
</div>

{% if submitted %}
    <p class="text-success">You have submit successfully! <a href="{% url 'rango:profile' user.username %}">Profile</a></p>
{% endif %}

        <form role="form" method="post" action="{% url 'rango:register_profile' %}"
              class="form-horizontal" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
            <label for="website" class="control-label">Website</label>
            <input type="text" class="form-control" name="website"
                       placeholder="website" id="Website" maxlength="30" />
            <label for="picture" class="control-label">Picture</label>
            <input type="file" class="form-control" name="picture" id="picture" />
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

{% endblock %}

templates/rango/profile_show.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}
    Profile List
{% endblock %}

{% block body %}
<div class="jumbotron">
    <h1>User Profiles</h1>
</div>
<div class="panel">
{% if users %}
    <div class="panel-heading">
        <div class="panel-body">
            <div class="list-group">
            {% for user in users %}
                <div class="list-group-item">
                    <h4 class="list-group-item-heading">
                        <a href="{% url 'rango:profile' user.username %}">{{ user.username }}</a>
                    </h4>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>
{% else %}
    <h3 class="text-warning">No body register yet...</h3>
{% endif %}
{% endblock %}
</div>

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <h1>About Page</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'rango:index' %}">Return to the hompage.</a>
    {% else %}
        Rango says: <strong>register here!</strong>
        <form id="user_form" method="post" action="{% url 'rango:register' %}"
              enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}